# Generated by Django 2.1.7 on 2020-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0003_auto_20200611_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='picPath',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_Type',
            field=models.CharField(choices=[('MC', 'MC'), ('FI', 'FI')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Quiz name'),
        ),
    ]
