# Generated by Django 2.1.7 on 2020-06-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0004_auto_20200613_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='displayName',
            field=models.CharField(default='Present Conjugations (Regular)', max_length=100, verbose_name='Display name'),
            preserve_default=False,
        ),
    ]
