# Generated by Django 2.1.7 on 2020-06-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0005_quiz_displayname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='picPath',
            new_name='imgPath',
        ),
        migrations.AddField(
            model_name='question',
            name='resourcePath',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
